name: FirstName

on: 
  workflow_dispatch: #manual start
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simple shell
        run: echo Hello fra meg step 1
      - name: Simple shell 2
        run: echo Hello fra meg step 2
        
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simple shell command step 
        run: echo Hello 

     

  third-job:
    runs-on: ubuntu-latest
    needs: [second-job]
    steps:
    - name: Simple shell command step 
      run: echo Hello 
      
      
    
    
